# Square Font Profile - Extends base font.yaml
extends: "font.yaml"

# Override specified values

font:
  family: "Kdr Mono Condensed"
  family_short: "KdrMonoCondensed"

# Width settings
width:
  half_width: 928
  full_width: 1856
  threshold: 1392

scale:
  half_width_x: 0.76
  full_width_x: 0.92