# Square Font Profile - Extends base font.yaml
extends: "font.yaml"

# Override specified values

font:
  family: "Kdr Mono Extended"
  family_short: "KdrMonoExtended"

scale:
  half_width_x: 0.91
  full_width_x: 1.06
