# Square Font Profile - Extends base font.yaml
extends: "font.yaml"

# Override specified values

font:
  family: "Kdr Mono Condensed"
  family_short: "KdrMonoCondensed"

# Width settings
width:
  half_width: 932
  full_width: 1864
  threshold: 1398

scale:
  half_width_x: 0.78
  full_width_x: 0.97