# Square Font Profile - Extends base font.yaml
extends: "font.yaml"

# Override specified values

font:
  family: "Kdr Mono Compact"
  family_short: "KdrMonoCompact"

scale:
  half_width_x: 0.73
  half_width_y: 0.82
  full_width_x: 0.87
  full_width_y: 0.87