# Square Font Profile - Extends base font.yaml
extends: "font.yaml"

# Override specified values

font:
  family: "Kdr Mono Narrow"
  family_short: "KdrMonoNarrow"

scale:
  half_width_x: 0.73
  full_width_x: 0.85